name: Get OS Release mac

on:
  push:
    paths:
      - ".github/workflows/mac-os-release.yml"

jobs:
  test:
    name: test
    runs-on: macos-latest
    steps:
      - name: uname
        run: uname -r

      - name: sw vers
        run: sw_vers -productVersion

      - name: product
        run: sw_vers -productName
        
